# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
destination: ../doc_outputs/mydoc/designers
topnav_title: Doc theme &mdash; designers
homepage_title: Jekyll doc theme for designers
site_title: Jekyll theme for designers
project_folder: doc

# variables

sidebar_tagline: Designers
sidebar_version: Version 4.0
theme_file: theme-blue.css
project_file_name: doc

port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false

suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: rouge

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true

sass:
    sass_dir: _sass
